# Generated by Django 5.2.3 on 2025-07-06 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('job_seeker', 'Job Seeker'), ('employer', 'Employer'), ('employer_staff', 'Employer Staff')], default='job_seeker', max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('education_level', models.CharField(blank=True, max_length=100, null=True)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('job_type', models.CharField(choices=[('full-time', 'Full Time'), ('part-time', 'Part Time'), ('internship', 'Internship'), ('freelance', 'Freelance')], default='full-time', max_length=50)),
                ('expected_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('resume_details', models.JSONField(blank=True, default=dict)),
                ('language_proficiency', models.JSONField(blank=True, default=dict)),
                ('portfolio_links', models.JSONField(blank=True, default=dict)),
                ('dob', models.DateField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('profile_visibility', models.CharField(choices=[('public', 'Public'), ('hide', 'Hide')], default='public', max_length=10)),
                ('registration_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('has_company_profile', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_groups', to='auth.group', verbose_name='groups')),
                ('parent_employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('org_type', models.CharField(choices=[('company', 'Company'), ('school', 'School'), ('college', 'College'), ('university', 'University'), ('training_center', 'Training Center'), ('ngo', 'NGO')], default='company', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organization_logos/')),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('industry_type', models.CharField(blank=True, max_length=100, null=True)),
                ('education_board', models.CharField(blank=True, max_length=100, null=True)),
                ('affiliated_university', models.CharField(blank=True, max_length=255, null=True)),
                ('established_year', models.IntegerField(blank=True, null=True)),
                ('org_size', models.CharField(blank=True, max_length=50, null=True)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('full-time', 'Full Time'), ('part-time', 'Part Time'), ('internship', 'Internship'), ('freelance', 'Freelance'), ('contract', 'Contract')], default='full-time', max_length=20)),
                ('experience_level', models.CharField(choices=[('fresher', 'Fresher'), ('mid', 'Mid Level'), ('senior', 'Senior Level')], default='fresher', max_length=20)),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True)),
                ('skills_required', models.JSONField(blank=True, default=list)),
                ('qualifications', models.TextField(blank=True, null=True)),
                ('application_deadline', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to='app.organization')),
            ],
        ),
    ]
