# Generated by Django 5.2.6 on 2025-10-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='category',
            field=models.CharField(choices=[('University', 'University'), ('College', 'College'), ('Higher Secondary', 'Higher Secondary'), ('Nursery & Primary', 'Nursery & Primary'), ('Middle School', 'Middle School'), ('Other', 'Other')], max_length=50),
        ),
    ]
