# Generated by Django 5.2.3 on 2025-07-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='category',
            field=models.CharField(choices=[('Nursery', 'Nursery'), ('Primary', 'Primary'), ('High School', 'High School'), ('College', 'College'), ('University', 'University'), ('Vocational', 'Vocational'), ('Other', 'Other')], max_length=50),
        ),
    ]
