# Generated by Django 5.2.3 on 2025-08-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
