# Generated by Django 5.2.6 on 2025-09-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='member_since',
            new_name='omeiat_member_since',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='avg_salary_non_teaching',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='avg_salary_teaching',
        ),
        migrations.AddField(
            model_name='institution',
            name='is_omeiat_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='consolidated_college_marksheet',
            field=models.FileField(blank=True, null=True, upload_to='consolidated_mark_sheets/'),
        ),
        migrations.AddField(
            model_name='user',
            name='graducation_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='hss_marksheet',
            field=models.FileField(blank=True, null=True, upload_to='hss_marksheets/'),
        ),
        migrations.AddField(
            model_name='user',
            name='sslc_marksheet',
            field=models.FileField(blank=True, null=True, upload_to='sslc_marksheets/'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='category',
            field=models.CharField(choices=[('Kindergarden', 'Kindergarden'), ('Nursery & Primary', 'Nuresery & Primary'), ('High School', 'High School'), ('College', 'College'), ('University', 'University'), ('Vocational', 'Vocational'), ('Other', 'Other')], max_length=100),
        ),
    ]
