# Generated by Django 5.2.3 on 2025-08-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mother_tongue',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
