# Generated by Django 5.2.6 on 2025-10-01 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_member_since_institution_omeiat_member_since_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='omeiatzones',
            name='description',
        ),
        migrations.RemoveField(
            model_name='omeiatzones',
            name='from_location',
        ),
        migrations.RemoveField(
            model_name='omeiatzones',
            name='to_location',
        ),
    ]
