# Generated by Django 5.2.3 on 2025-07-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_jobcategory_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='experience',
            field=models.PositiveIntegerField(blank=True, help_text='Experience in years', null=True),
        ),
    ]
