# Generated by Django 5.2.6 on 2025-10-31 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_institution_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institutionapproval',
            options={'ordering': ['-approved_at'], 'verbose_name': 'Institution Approval', 'verbose_name_plural': 'Institution Approvals'},
        ),
        migrations.AlterField(
            model_name='institutionapproval',
            name='approved_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_superuser': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_institutions', to=settings.AUTH_USER_MODEL),
        ),
    ]
