# Generated by Django 5.2.6 on 2025-10-31 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_institutionapproval_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='omeiat_member_since',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
