# Generated by Django 5.2.6 on 2025-10-04 05:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_omeiatzones_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OmeiatZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Omeiat Zones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Permissions',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('job_seeker', 'Job Seeker'), ('institution', 'Institution'), ('admin', 'Admin')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.RenameField(
            model_name='job',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='workexperience',
            old_name='name',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='workexperience',
            old_name='from_date',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='address',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='city',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='coordinator_name',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='correspondent_name',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='country',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='district',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='founder_name',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='no_of_boys',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='no_of_gents_staff',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='no_of_girls',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='no_of_ladies_staff',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='no_of_non_teaching_staff',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='no_of_students',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='principal_name',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='recruitment_contact',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='state',
        ),
        migrations.RemoveField(
            model_name='job',
            name='qualifications',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary_max',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary_min',
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('applicant', 'job')},
        ),
        migrations.RemoveField(
            model_name='user',
            name='about_family',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='aim_of_life',
        ),
        migrations.RemoveField(
            model_name='user',
            name='consolidated_college_marksheet',
        ),
        migrations.RemoveField(
            model_name='user',
            name='describing_experience',
        ),
        migrations.RemoveField(
            model_name='user',
            name='expected_salary',
        ),
        migrations.RemoveField(
            model_name='user',
            name='graducation_percentage',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hss_marksheet',
        ),
        migrations.RemoveField(
            model_name='user',
            name='joining_availability',
        ),
        migrations.RemoveField(
            model_name='user',
            name='languages_known',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_salary',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mother_tongue',
        ),
        migrations.RemoveField(
            model_name='user',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reference_by_1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reference_by_2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='schooling',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sslc_marksheet',
        ),
        migrations.RemoveField(
            model_name='user',
            name='working_experience_years',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='post_assigned',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='to_date',
        ),
        migrations.AddField(
            model_name='institution',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='institution',
            name='is_otp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institution',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='institution_logos/'),
        ),
        migrations.AddField(
            model_name='institution',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='job',
            name='candidate_gender',
            field=models.CharField(choices=[('Any', 'Any'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Any', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='degree_required',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='interview_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_timing',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='location_range_km',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='max_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='min_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='no_of_openings',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='job',
            name='qualifications_required',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], default='Open', max_length=50),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='commute_distance_km',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_match_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='joining_availability',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='response',
            field=models.CharField(choices=[('applied', 'Applied'), ('interviewed', 'Interviewed'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='applied', max_length=50),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_otp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='institution',
            name='board',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='category',
            field=models.CharField(choices=[('Kindergarten', 'Kindergarten'), ('Nursery & Primary', 'Nursery & Primary'), ('High School', 'High School'), ('College', 'College'), ('University', 'University'), ('Vocational', 'Vocational'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='institution',
            name='omeiat_member_since',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='year_established',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='application_deadline',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience_needed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='app.institution'),
        ),
        migrations.RemoveField(
            model_name='job',
            name='skills_required',
        ),
        migrations.AlterField(
            model_name='job',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='app.institution'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='app.job'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('job_posted', 'Job Posted'), ('application_status', 'Application Status Updated'), ('shortlisted', 'Shortlisted for Job'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('system', 'System Alert'), ('info', 'Info')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('SSLC', 'SSLC'), ('HSS', 'HSS'), ('Diploma', 'Diploma'), ('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PhD', 'PhD'), ('Other', 'Other')], max_length=50)),
                ('institution', models.CharField(max_length=255)),
                ('degree', models.CharField(blank=True, max_length=255, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='certifications_required',
            field=models.ManyToManyField(blank=True, to='app.education'),
        ),
        migrations.CreateModel(
            name='EmployerReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('review', models.TextField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app.institution')),
            ],
            options={
                'verbose_name_plural': 'Employer Reviews',
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_no', models.CharField(blank=True, max_length=50, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='app.institution')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('HR', 'HR'), ('Admin', 'Admin'), ('Principal', 'Principal'), ('Coordinator', 'Coordinator'), ('Correspondent', 'Correspondent'), ('Founder', 'Founder')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='app.institution')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionStrength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students_male', models.PositiveIntegerField(default=0)),
                ('students_female', models.PositiveIntegerField(default=0)),
                ('teachers_male', models.PositiveIntegerField(default=0)),
                ('teachers_female', models.PositiveIntegerField(default=0)),
                ('non_teaching_staff', models.PositiveIntegerField(default=0)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='strength', to='app.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('proficiency', models.CharField(blank=True, choices=[('Basic', 'Basic'), ('Fluent', 'Fluent'), ('Native', 'Native')], max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='institution',
            name='omeiat_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.omeiatzone'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='app.role'),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='app.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='app.role')),
            ],
            options={
                'verbose_name_plural': 'Role Permissions',
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert')], max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_no', models.CharField(blank=True, max_length=50, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='job',
            name='skills_required',
            field=models.ManyToManyField(blank=True, to='app.skill'),
        ),
        migrations.DeleteModel(
            name='OmeiatZones',
        ),
    ]
