# Generated by Django 5.2.6 on 2025-10-05 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_omeiatzone_permission_role_rename_name_job_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='app/static/institution_logos/'),
        ),
    ]
