# Generated by Django 5.2.3 on 2025-07-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_jobapplication_cover_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10),
        ),
    ]
