# Generated by Django 5.2.6 on 2025-10-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_institution_about_alter_institution_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='communication_skills',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='qualification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='technical_skills',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
