# Generated by Django 5.2.6 on 2025-10-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_jobapplication_communication_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='joining_availability',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
