# Generated by Django 5.2.3 on 2025-07-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_organization_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='gender',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10),
        ),
    ]
