# Generated by Django 5.2.6 on 2025-10-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_jobapplication_joining_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='app/static/profiles/'),
        ),
    ]
