name: Django CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: omeiat_db
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config default-libmysqlclient-dev
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run migrations
        env:
          SECRET_KEY: omeiatjobportalandfreeapp
          DEBUG: True
          MYSQL_HOST: localhost
          MYSQL_PORT: 3306
          MYSQL_DATABASE: omeiat_db
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1,testserver
        run: python manage.py migrate
        
      - name: Run tests
        env:
          SECRET_KEY: omeiatjobportalandfreeapp
          DEBUG: True
          MYSQL_HOST: localhost
          MYSQL_PORT: 3306
          MYSQL_DATABASE: omeiat_db
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1,testserver
        run: python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT || '22' }}
          script: |
            echo "🚀 Starting Omeiat deployment..."
            
            cd /var/www/Omeiat
            
            # Pull latest changes
            git fetch origin
            git reset --hard origin/main
            
            # Activate virtual environment
            source venv/bin/activate

            # Install dependencies
            pip install -r requirements.txt
            
            # Run migrations and collectstatic
            python manage.py migrate
            python manage.py collectstatic --noinput

            # Ensure environment variables
            export DJANGO_ALLOWED_HOSTS="www.nexgen-e.com,nexgen-e.com,127.0.0.1,localhost"
            export SECRET_KEY="${{ secrets.DJANGO_SECRET_KEY }}"
            export DEBUG=False
            
            # Restart Gunicorn service
            sudo systemctl daemon-reload
            sudo systemctl restart omeiat
            
            echo "✅ Omeiat deployment completed successfully!"
